apiVersion: tekton.dev/v1beta1
kind: Task
metadata:

  name: helm-upgrade-from-git

spec:

  description: These tasks will install / upgrade a helm chart into your Kubernetes / OpenShift Cluster using Helm

  params:

    - description: Specify chart location in git repo
      name: helm_dir
      type: string

    - default: helm-release
      description: The helm release name
      name: release_name
      type: string

    - default: ''
      description: The helm release namespace
      name: release_namespace
      type: string

    - default: ''
      description: 'Specify the values you want to overwrite, comma separated: autoscaling.enabled=true,replicas=1'
      name: overwrite_values
      type: string

    - default: ''
      description: 'Specify the image name to overwrite'
      name: image_tag
      type: string

    - default: 'docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae'
      description: Specify a specific helm image
      name: helm_image
      type: string

  steps:
    - image: $(params.helm_image)
      name: helm-github-upgrade
      resources: {}
      script: |
        ls -la 
        
        cat Chart.yaml

        cat values.yaml

        SHORT_COMMIT_ID=$(echo $(params.image_tag) | cut -c 1-7)

        helm upgrade --wait --install --namespace "$(params.release_namespace)" "$(params.release_name)" . --debug --set image.tag="${SHORT_COMMIT_ID}" ",$(params.overwrite_values)"

      workingDir: $(workspaces.source.path)/$(params.helm_dir)

  workspaces:
    - description: The git repo will be cloned onto the volume backing this Workspace.
      name: source