apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: spring-boot-todo
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: github-triggerbind
      interceptors:
        - params:
            - name: eventTypes
              value:
                - pull_request
                - push
            - name: addChangedFiles
              value:
                enabled: true
          ref:
            apiVersion: triggers.tekton.dev
            kind: ClusterInterceptor
            name: github
        - params:
            - name: filter
              value: extensions.changed_files.matches('springboot-todo/src/')
          ref:
            kind: ClusterInterceptor
            name: cel
      template:
        ref: spring-boot-todo-trigger