kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-spring-boot-todo
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: spring-boot-todo
spec:
  subdomain: el-spring-boot-todo
  to:
    kind: Service
    name: el-spring-boot-todo
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None