apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: spring-boot-todo-trigger
spec:
  params:
    - name: GIT_HEADCOMMIT_ID
    - name: GIT_URL
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: spring-boot-todo-
        labels:
          tekton.dev/pipeline: spring-boot-todo
      spec:
        params:
          - name: GIT_SOURCECODE_URL
            value: 'https://github.com/mugicoder13/spring-boot-todo.git'
          - name: GIT_SOURCECODE_REVISION
            value: development
          - name: SOURCECODE_DIR
            value: .
          - name: DOCKERFILE_PATH
            value: Dockerfile
          - name: GIT_DEPLOYMENT_MANIFESTS_URL
            value: 'https://github.com/mugicoder13/observai-gitops.git'
          - name: GIT_DEPLOYMENT_MANIFESTS_REVISION
            value: main
          - name: DEPLOYMENT_MANIFESTS_DIR
            value: kustomize/overlays/dev
          - name: GIT_USER_NAME
            value: mukesh1327
          - name: GIT_USER_EMAIL
            value: mugicoder13@gmail.com
          - name: IMAGE
            value: quay.io/mugicoder13/spring-boot-todo-observai
          - name: OLD_IMAGE
            value: $(params.IMAGE)
          - name: IMAGE_TAG_COMMITID
            value: $(tt.params.GIT_HEADCOMMIT_ID)
          - name: IMAGE_TAG_ENV
            value: java-

        pipelineRef:
          name: spring-boot-todo

        workspaces:
          - name: sourcecode
            persistentVolumeClaim:
              claimName: spring-boot-todo-ci

          - name: deployment-manifests
            persistentVolumeClaim:
              claimName: spring-boot-todo-cd