apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: spring-boot-todo-trigger
spec:
  params:
    - name: GIT_HEADCOMMIT_ID
    - name: GIT_URL
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: spring-boot-todo-
        labels:
          tekton.dev/pipeline: spring-boot-todo
      spec:
        params:
          - name: GIT_SOURCECODE_URL
            value: 'https://github.com/mukesh1327/tekton-sample-pipeline.git'

          - name: GIT_SOURCECODE_REVISION
            value: main

          - name: SOURCECODE_DIR
            value: springboot-todo

          - name: DOCKERFILE_PATH
            value: springboot-todo/Dockerfile

          - name: GIT_USER_NAME
            value: mukesh1327

          - name: GIT_USER_EMAIL
            value: mugicoder13@gmail.com

          - name: IMAGE
            value: quay.io/mukeshs1306/springboot-todo-app

          - name: IMAGE_TAG_COMMITID
            value: $(tt.params.GIT_HEADCOMMIT_ID)

        pipelineRef:
          name: spring-boot-todo

        workspaces:
          - name: sourcecode
            persistentVolumeClaim:
              claimName: spring-boot-todo-ci