kind: Secret
apiVersion: v1
metadata:
  name: {{ include "todo-app.fullname" . }}

  labels:
    {{- include "todo-app.labels" . | nindent 4 }}

data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}

type: Opaque
