apiVersion: tekton.dev/v1
kind: Pipeline
metadata:

  labels:
    app.kubernetes.io/instance: springboot-todo-s2i-git
    app.kubernetes.io/name: springboot-todo-s2i-git
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/runtime: java
    pipeline.openshift.io/runtime-version: openjdk-17-ubi8

  name: springboot-todo-s2i-git
  namespace: vps-apps

spec:


  params:
    - default: springboot-todo-s2i-git
      name: APP_NAME
      type: string
    - default: 'https://github.com/mukesh1327/tekton-sample-pipeline.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/vps-apps/springboot-todo-s2i-git'
      name: IMAGE_NAME
      type: string
    - default: springboot-todo
      name: PATH_CONTEXT
      type: string
    - default: openjdk-17-ubi8
      name: VERSION
      type: string


  tasks:


    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace


    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: workspace


    - name: deploy
      params:
        - name: SCRIPT
          value: oc rollout status deploy/$(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client


  workspaces:
    - name: workspace
