# Generated by Django 4.2.5 on 2023-09-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourEntity',
            new_name='tasks',
        ),
    ]
