# Generated by Django 4.2.5 on 2023-09-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotodo', '0002_rename_yourentity_tasks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasks',
            table='tasks',
        ),
    ]
