# Generated by Django 4.2.2 on 2023-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotodo', '0003_alter_tasks_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE'), ('DROPPED', 'DROPPED'), ('KILLED', 'KILLED')], default='IN_PROGRESS', max_length=20),
        ),
    ]
