apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

- ./resources/deployment.yaml
- ./resources/service.yaml

commonLabels:
  app.kubernetes.io/part-of: spring-boot-todo
  app.kubernetes.io/managed-by: kustomize